# Generated by Django 3.2.8 on 2021-10-30 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TiendaOnline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='actualizacion',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='creacion',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='dpi',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='total',
        ),
        migrations.AddField(
            model_name='orden',
            name='clienteo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orden',
            name='completo',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='transaccion_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='DireccionEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('apellido', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('tel', models.CharField(max_length=300)),
                ('direccion', models.CharField(max_length=300)),
                ('dpi', models.CharField(max_length=300)),
                ('product', models.CharField(max_length=300)),
                ('total', models.CharField(max_length=300)),
                ('creacion', models.DateField(auto_now_add=True)),
                ('actualizacion', models.DateField(auto_now_add=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('clientea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TiendaOnline.orden')),
            ],
        ),
    ]
